import type { ReactNode } from "react";
import { ChevronDown, CircleAlert } from "lucide-react";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

export interface SelectOption {
  value: string;
  label: string;
}

interface SelectFieldProps {
  id: string;
  name?: string;
  label: string;
  value: string;
  onChange: (value: string) => void;
  options: SelectOption[];
  /** Rendered as a disabled, empty-valued first option. */
  placeholder?: string;
  error?: string;
  /**
   * No caller passes this yet. It is here because the point of this component
   * is to mirror `FormField`'s contract exactly — a form mixing the two must
   * not offer a hint on one control and not the other. Do not remove it as
   * dead code.
   */
  hint?: ReactNode;
}

/**
 * A labelled native `<select>` carrying the same error, hint and aria contract
 * as `FormField`, so the two sit on one form without looking like two component
 * systems.
 *
 * Native rather than a Radix listbox for two reasons: the OS wheel picker is
 * the right control for this app's stated moment of use — a phone, one hand, at
 * the doctor's — and adding a primitive under `src/components/ui/` would
 * collide with the medications slice building in a sibling worktree. It lives
 * in `src/components/form/` for the same reason `FormField` does: that
 * directory is ours to edit, `src/components/ui/` is generated by shadcn and
 * is not.
 *
 * The styling is `Input`'s, token for token — `border-input`, the same focus
 * ring, the same `aria-invalid` treatment — rather than a hardcoded colour.
 */
export function SelectField({ id, name, label, value, onChange, options, placeholder, error, hint }: SelectFieldProps) {
  const errorId = `${id}-error`;
  const hintId = `${id}-hint`;
  const describedBy = error ? errorId : hint ? hintId : undefined;

  return (
    <div>
      <Label htmlFor={id} className="text-muted-foreground mb-1.5">
        {label}
      </Label>
      <div className="relative">
        <select
          id={id}
          name={name ?? id}
          value={value}
          onChange={(e) => {
            onChange(e.target.value);
          }}
          aria-invalid={error ? true : undefined}
          aria-describedby={describedBy}
          className={cn(
            // Token-for-token with `src/components/ui/input.tsx`, the `dark:`
            // variants included. That block in `global.css` is dead today, but
            // a select that only matches `Input` in light mode is exactly the
            // drift this component exists to prevent.
            "border-input placeholder:text-muted-foreground dark:bg-input/30 h-9 w-full min-w-0 appearance-none rounded-md border bg-transparent py-1 pr-9 pl-3 text-base shadow-xs transition-[color,box-shadow] outline-none disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
            "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
            "aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40",
          )}
        >
          {placeholder ? (
            <option value="" disabled>
              {placeholder}
            </option>
          ) : null}
          {options.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
        {/* `appearance-none` removes the platform arrow; this restores one.
            Decorative and never the only cue that this is a select — the
            control still opens the OS picker on touch and responds to the
            keyboard exactly as a native select does. */}
        <ChevronDown
          aria-hidden="true"
          className="text-muted-foreground pointer-events-none absolute top-1/2 right-3 size-4 -translate-y-1/2"
        />
      </div>
      {/* As in `FormField`: the message conveys the error, the red border is a
          redundant cue and never the only one. */}
      {error ? (
        <p id={errorId} className="text-destructive mt-1 flex items-center gap-1 text-xs">
          <CircleAlert className="size-3 shrink-0" />
          {error}
        </p>
      ) : hint ? (
        <div id={hintId}>{hint}</div>
      ) : null}
    </div>
  );
}
